### ISSUE TITLE
data output into `src/_data/` folder

### ISSUE THREAD

**Issue by matikin9** [LACMTA/gopass-lookup#19]
@albertkun - I think I mentioned thinking about this issue last week but I didn't think of this super simple solution... 🤦 

Can you have the Jupyter Notebook put the final JSON data file into the `src/_data/` folder?  11ty will be able to access it from there. We don't need the rest of the data files or the notebooks folder under `src/`. Since it will just be the one file, we can just name the file `schools.json`, unless you think that will be an issue?

![image](https://user-images.githubusercontent.com/1873072/183473514-671c29fc-2a6d-43f4-b14c-042f75a0a67c.png)

**Comment by albertkun** [comment]
Sounds good! This  PR #18 addresses this issue!
