### ISSUE TITLE
School named "District Office"?

### ISSUE THREAD

**Issue by matikin9** [LACMTA/gopass-lookup#34]
![image](https://user-images.githubusercontent.com/1873072/188024583-b76f46e9-054e-49ac-8ce5-30e8b800e06a.png)

**Comment by albertkun** [comment]
Unfortunately, this is from our Metro data list :(

https://docs.google.com/spreadsheets/d/1WLoM1h2PtmZpChgMkSDQ4gGOQXe3Y3fc0QKmasgu2pU/edit?ouid=116697866947381976050&usp=sheets_home&ths=true
